# Render YAML configuration for the backend

services:
  - type: web
    name: Backend Service
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "your-database-url"
    autoDeploy: true
